"""Shared company folder slug sanitization (CR-025) and display-name resolution (CR-048)."""
from __future__ import annotations

import os
import re
import sqlite3
from typing import Optional

_JD_SKIP_LINES = frozenset(
    {
        "jobs",
        "job posted",
        "posted",
        "the role",
        "summary generated by built in",
        "in-office or remote",
        "remote",
        "hybrid",
        "onsite",
    }
)


def sanitize_company_slug(company: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", (company or "").lower()).strip("_")
    if not slug:
        import hashlib

        slug = "company_" + hashlib.md5(company.encode("utf-8")).hexdigest()[:12]
    if not slug or ".." in slug or slug.startswith("."):
        raise ValueError(f"Invalid company name for folder slug: {company!r}")
    return slug


def company_submission_dir(base_dir: str, company: str) -> str:
    slug = sanitize_company_slug(company)
    folder = os.path.join(base_dir, slug)
    base_real = os.path.realpath(base_dir)
    folder_real = os.path.realpath(folder)
    if folder_real != base_real and not folder_real.startswith(base_real + os.sep):
        raise ValueError(f"Path traversal blocked for company: {company!r}")
    return folder


def _looks_like_slug(name: str) -> bool:
    return bool(name) and "_" in name and " " not in name


def _slug_title_fallback(slug_or_name: str) -> str:
    return slug_or_name.replace("_", " ").strip().title()


def company_name_from_jd(jd_text: str) -> Optional[str]:
    """Extract employer display name from the first plausible JD header line."""
    if not jd_text:
        return None
    for raw in jd_text.splitlines()[:20]:
        line = raw.strip()
        if not line or len(line) < 2 or len(line) > 80:
            continue
        low = line.lower()
        if low.startswith("url:") or line.startswith("http"):
            continue
        if low in _JD_SKIP_LINES or low.startswith("job posted"):
            continue
        if low.endswith("?"):
            continue
        if re.match(r"^\d", line):
            continue
        if re.match(r"^(product manager|software engineer|director|senior|staff)\b", low):
            continue
        if re.match(r"^[A-Z0-9]", line):
            return line.strip()
    return None


def _company_from_sqlite(db_path: str, company_key: str, job_id: Optional[str] = None) -> Optional[str]:
    if not db_path or not os.path.exists(db_path):
        return None
    try:
        conn = sqlite3.connect(db_path)
        if job_id:
            row = conn.execute(
                "SELECT company FROM jobs WHERE id LIKE ? LIMIT 1",
                (f"{job_id[:8]}%",),
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT company FROM jobs WHERE LOWER(company) = LOWER(?) OR LOWER(company) = LOWER(?) LIMIT 1",
                (company_key, company_key.replace("_", " ")),
            ).fetchone()
        conn.close()
        if row and row[0] and str(row[0]).strip():
            return str(row[0]).strip()
    except sqlite3.Error:
        return None
    return None


def resolve_company_display_name(
    company_key: str,
    *,
    company_folder: Optional[str] = None,
    jd_text: str = "",
    db_path: Optional[str] = None,
    job_id: Optional[str] = None,
    explicit_display: Optional[str] = None,
) -> str:
    """
    Resolve human-readable company name for cover letters (FR-103, CR-048).

    Priority: explicit override → Original_JD.txt header → JD text header →
    SQLite jobs.company → slug title fallback.
    """
    if explicit_display and str(explicit_display).strip():
        return str(explicit_display).strip()

    if company_folder:
        jd_path = os.path.join(company_folder, "Original_JD.txt")
        if os.path.isfile(jd_path):
            try:
                with open(jd_path, encoding="utf-8") as f:
                    from_jd_file = company_name_from_jd(f.read())
                if from_jd_file:
                    return from_jd_file
            except OSError:
                pass

    from_jd = company_name_from_jd(jd_text)
    if from_jd:
        return from_jd

    from_db = _company_from_sqlite(db_path or "", company_key, job_id)
    if from_db:
        return from_db

    key = (company_key or "").strip()
    if not key:
        return ""
    if _looks_like_slug(key):
        return _slug_title_fallback(key)
    return key
