#!/usr/bin/env python3
"""
Generate the lean authoring rule digest for CR-074.
# Implements FR-254, NFR-007

Writes:
  data/authoring_rule_digest.md        — the rule digest (no PII; tracked is fine)
  data/authoring_rule_digest.version   — first 16 hex chars of sha256(content)

Also available as a module: generate_digest() returns (content, version_str).

Usage:
    python scripts/generate_authoring_rule_digest.py
    python scripts/generate_authoring_rule_digest.py --check  # size check only, no write

Exit: 0 on success, 1 if content exceeds 10000-char hard limit.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).parent
_REPO_ROOT = _SCRIPT_DIR.parent
_DIGEST_PATH = _REPO_ROOT / "data" / "authoring_rule_digest.md"
_VERSION_PATH = _REPO_ROOT / "data" / "authoring_rule_digest.version"

# Hard ceiling — fail the generator above this, so callers notice immediately
_HARD_CHAR_LIMIT = 10_000
# Target (warn but don't fail if between TARGET and HARD)
_SOFT_CHAR_TARGET = 8_000

# ---------------------------------------------------------------------------
# The digest content is hardcoded here — no reads of PII files (workExperience.md,
# aiProjects.md, master_claims.json).  All process rules only.
# ---------------------------------------------------------------------------

_DIGEST_CONTENT = """\
# Authoring Rule Digest — CR-074
<!-- Implements FR-254, NFR-007 -->
<!-- Generated by scripts/generate_authoring_rule_digest.py — do not hand-edit -->

This digest is the lean authoring reference loaded by the cloud compose pass.
Load this + the authoring packet; do NOT load agent_context_pack.md, full CLAUDE.md,
or the full claims catalog.

---

## 1. Closed-World Rule (hardest constraint)

Use ONLY claim_ids, excerpts, and claim_constraints from the authoring packet.
Excerpts are retrieved workExperience.md (or aiProjects.md) spans, not catalog text.
Write fresh prose from those facts. Obey each card's Attribution and Prohibited
fields. Never round CONTRIBUTED into OWNED. Never invent a metric, tool, company
name, team name, or date not present in the packet. If the packet has no evidence
for a JD item, note the gap in soft_gaps — do not fabricate a claim to fill it.

---

## 1b. Optimization bar (hard — Round 4)

Done is NOT "clears rubric 70/65." Done is: every soft_gap / domain soft stretch uses the
packet's mapped claim_ids (strongest honest bridge); never substitute a weaker proxy when
that bridge excerpt is present; hard gaps are never claimed as owned. Rubric 70/65 is a
floor check after the bridges are in — not the stop condition. Prefer the JD's bare honest
base title only (no borrowed domain qualifier). Bullets stay ~2–3 lines for scan.

---

## 2. Resume Structure

**Section order (exact headings required):**

```
# [Name]
[contact line]

## PROFESSIONAL SUMMARY
[exactly 3 sentences]

## CORE COMPETENCIES          ← optional; omit if not used
[skills row]

## PROFESSIONAL EXPERIENCE
### [Title] | [Company] | [Start] - [End]
[Location]
* [bullet]

## EDUCATION
[degree line]
```

**Summary rules:**
- Exactly 3 sentences — not 2, not 4.
- Summary characterizes the professional (positioning, scope, how he works). It is NOT the place for achievements.
- If a proof sentence is needed: at most 1. Preferred default: 0 proof sentences.
- Never recite the full cross-functional partner list — say "cross-functionally."
- The heading must be literally `## PROFESSIONAL SUMMARY` — no substitutions.
- Optional bold subtitle must mirror THIS JD's framing. Never default to "B2B SaaS Platform Product Manager."
- HARD_BLOCK (LR-031): do not put "B2B SaaS" in the summary (subtitle or body) unless Original_JD.txt itself uses the word "SaaS." If the JD does not say SaaS, use the JD's own framing or drop the label.

**1-page hard rule:** Resume PDF must fit on exactly one page. No extra sections beyond the four above.

**All 3 canonical roles must appear:**
- Cision (most recent)
- Sterkly
- Zero To Sixty

Bullet counts: most-recent role 5–6; earlier roles 2–3 each.

---

## 3. Resume Bullet Rules

- Order bullets by JD-relevance first. Among equally-relevant bullets, prefer the one with a hard metric.
- Lead with the metric when a bullet carries one — put the number close to the verb, not at the end.
- Bullet length: ~2–3 lines. No multi-sentence blocks.
- Do NOT list a team (Engineering, DBA, etc.) as a cross-functional partner unless it appears in the verified list: Engineering, DBA, DevOps, Customer Experience (CX), Customer Support, Sales, Account Management, Legal, InfoSec, Product Marketing, Executive/Presidential Leadership, Upgrades.
- Never use internal codenames. VOC translations (required):
  - "Airo" → "a macOS security product"
  - "Platform Data Remediation" → "centralized platform data remediation initiative"
  - "Core B2B SaaS Platform" → "customer-facing B2B SaaS media monitoring and contact database platform"
  - "Centralized Contact Database" → "centralized contact source-of-truth database"
  - "Critical Save Program" → "high-risk account retention program"
  - "White Glove Accounts" → "premium high-revenue enterprise clients"

---

## 4. Cover Letter Structure

```
# [Name]
[contact line]

Dear Hiring Manager,

[body paragraphs — no bullet points]

Best regards,

[Name]
```

- 250–400 words body.
- No bullet points anywhere in the letter.
- Opening hook: something specific to the company or role, not generic enthusiasm.
  Do NOT open with "I am writing to express my interest."

---

## 5. Cover Letter Argument Rules

- Argue fit only. Never acknowledge a gap, skill absence, or inexperience.
- No gap-confession language: "is new territory for me," "I have not yet," "are new to me," or any variant.
- Do NOT build any argument around workforce reduction, headcount shrinking, executive turnover,
  or "operating through constraint" via team size — not even via an approved euphemism.
- Do NOT assert fit with: "maps directly," "exact fit," "perfectly suited," "uniquely qualified."
  Show fit with a specific fact instead.
- Do NOT paraphrase the JD's own prose back to the reader as the opening hook.

---

## 6. Attribution Tiers

Apply the correct tier to every ACC code used:

| Tier | Meaning | Example phrasing |
|---|---|---|
| OWNED | Jason built, designed, or led it | "I led…", "I designed…", "I owned…" |
| CONTRIBUTED | Joint or adjacent work | "I contributed to…", "I partnered on…" |
| INFLUENCED | Informed without direct ownership | "I provided input on…" |

**ACC-120 (AI content-generation system):** CONTRIBUTED at most — joint prompt-engineering research only.
Jason did NOT build or design the AI system. Never write "I built" or "I designed" about it.
When `claim_constraints` lists a tier for a claim_id, that card wins over this table.

---

## 7. Forbidden Formatting

- **Em dash (—):** never, anywhere — including mid-sentence.
- **Semicolons (;):** never in resumes or cover letters. Split into two sentences.
- **Colon-as-elaboration:** do not use `word: word` as a prose em-dash substitute
  (e.g., "compelling: building", "context: how"). Resume label colons (`**Skills:** …`) are fine.
- **Double-hyphen (--):** never.
- **Bullet points in cover letters:** never.

---

## 8. Forbidden Words and Phrases (core list)

Never use: leverage, passionate, driven, dynamic, innovative, seamless, transformative, synergy,
tapestry, revolutionize, revenue-bearing, proven track record, layoff(s), I am excited to apply,
I am excited about, I am confident that, Furthermore, Moreover, In addition, Additionally.

Never open a sentence with: Furthermore, Moreover, In addition, Additionally, However (as opener),
Here's the thing, Ultimately (as opener), Overall (as opener).

The full enforced list lives in `scripts/submission_linter.py` rules LR-009, LW-006, LW-007.
This section is the always-hard-blocked core, not the exhaustive set.

---

## 9. Exclusion Zones — What Jason Is NOT

Never claim any of the following, regardless of JD language:

- People management, direct reports, hiring/firing, or managing other PMs
- Titles above Senior IC PM (no Director, Head of, Principal, VP, Staff, Group PM)
- AI/ML model training, ownership, or engineering
- Revenue, billing, or payment system ownership
- Tools not in his history (no Snowflake, Tableau, FHIR, Kubernetes, TensorFlow, etc.
  unless explicitly present in the packet excerpt)
- "Familiar with," "awareness of," or "literacy in" any tool (if not a hard skill in packet, it doesn't exist)

---

## 10. Collaboration Framing

Jason works through influence and alignment, not authority. Use:
- "built alignment across," "brought teams to a shared order of priorities,"
  "got everyone to commit to," "aligned X and Y on."

Never: forced, made, imposed, or drove other teams "into" a decision.

---
"""


def _version_from_content(content: str) -> str:
    """Return first 16 hex chars of sha256(utf-8 content)."""
    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
    return digest[:16]


def generate_digest() -> tuple[str, str]:
    """Return (content, version_str) without writing any files.

    Raises ValueError if content exceeds _HARD_CHAR_LIMIT.
    """
    content = _DIGEST_CONTENT
    n = len(content)
    if n > _HARD_CHAR_LIMIT:
        raise ValueError(
            f"Digest content is {n} chars, exceeds hard limit of {_HARD_CHAR_LIMIT}. "
            "Trim the digest before proceeding."
        )
    version = _version_from_content(content)
    return content, version


def write_digest(
    digest_path: Path | None = None,
    version_path: Path | None = None,
) -> tuple[str, str]:
    """Generate and write the digest + version files.

    Returns (content, version_str).
    Raises ValueError if content exceeds hard limit.
    """
    content, version = generate_digest()
    dp = digest_path or _DIGEST_PATH
    vp = version_path or _VERSION_PATH
    dp.parent.mkdir(parents=True, exist_ok=True)
    dp.write_text(content, encoding="utf-8")
    vp.write_text(version, encoding="utf-8")
    return content, version


def _main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the lean authoring rule digest (CR-074 Epic 4.2).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check size only — print char count and version, do not write files.",
    )
    args = parser.parse_args()

    try:
        content, version = generate_digest()
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    n = len(content)
    if n > _SOFT_CHAR_TARGET:
        print(
            f"WARNING: digest is {n} chars (over soft target of {_SOFT_CHAR_TARGET}; "
            f"hard limit is {_HARD_CHAR_LIMIT}).",
            file=sys.stderr,
        )

    if args.check:
        print(f"chars={n}  version={version}")
        sys.exit(0)

    content, version = write_digest()
    n = len(content)
    print(f"Written: {_DIGEST_PATH}")
    print(f"Written: {_VERSION_PATH}")
    print(f"chars={n}  approx_tokens={n // 4}  version={version}")
    sys.exit(0)


if __name__ == "__main__":
    _main()
